
package net.spring.intranet.servicio.Carrera;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarreraService", targetNamespace = "http://service.intranet.spring.net", wsdlLocation = "http://localhost:8080/School_Servidor/services/CarreraService?wsdl")
public class CarreraService
    extends Service
{

    private final static URL CARRERASERVICE_WSDL_LOCATION;
    private final static WebServiceException CARRERASERVICE_EXCEPTION;
    private final static QName CARRERASERVICE_QNAME = new QName("http://service.intranet.spring.net", "CarreraService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/School_Servidor/services/CarreraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARRERASERVICE_WSDL_LOCATION = url;
        CARRERASERVICE_EXCEPTION = e;
    }

    public CarreraService() {
        super(__getWsdlLocation(), CARRERASERVICE_QNAME);
    }

    public CarreraService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARRERASERVICE_QNAME, features);
    }

    public CarreraService(URL wsdlLocation) {
        super(wsdlLocation, CARRERASERVICE_QNAME);
    }

    public CarreraService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARRERASERVICE_QNAME, features);
    }

    public CarreraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarreraService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpSoap11Endpoint")
    public CarreraServicePortType getCarreraServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpSoap11Endpoint"), CarreraServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpSoap11Endpoint")
    public CarreraServicePortType getCarreraServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpSoap11Endpoint"), CarreraServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpSoap12Endpoint")
    public CarreraServicePortType getCarreraServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpSoap12Endpoint"), CarreraServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpSoap12Endpoint")
    public CarreraServicePortType getCarreraServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpSoap12Endpoint"), CarreraServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpEndpoint")
    public CarreraServicePortType getCarreraServiceHttpEndpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpEndpoint"), CarreraServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarreraServicePortType
     */
    @WebEndpoint(name = "CarreraServiceHttpEndpoint")
    public CarreraServicePortType getCarreraServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "CarreraServiceHttpEndpoint"), CarreraServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARRERASERVICE_EXCEPTION!= null) {
            throw CARRERASERVICE_EXCEPTION;
        }
        return CARRERASERVICE_WSDL_LOCATION;
    }

}
