
package net.spring.intranet.servicio.Carrera;


import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.spring.intranet.entidad.Carrera.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarreraServicePortType", targetNamespace = "http://service.intranet.spring.net")
@XmlSeeAlso({
    net.spring.intranet.entidad.Carrera.ObjectFactory.class,
    net.spring.intranet.servicio.Carrera.ObjectFactory.class
})
public interface CarreraServicePortType {


    /**
     * 
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.Carrera>
     */
    @WebMethod(action = "urn:listaCarreras")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaCarreras", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaCarreras")
    @ResponseWrapper(localName = "listaCarrerasResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaCarrerasResponse")
    public List<Carrera> listaCarreras();

}
