
package net.spring.intranet.servicio.Seccion;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.spring.intranet.entidad.Seccion.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeccionServicePortType", targetNamespace = "http://service.intranet.spring.net")
@XmlSeeAlso({
    net.spring.intranet.entidad.Seccion.ObjectFactory.class,
    net.spring.intranet.servicio.Seccion.ObjectFactory.class
})
public interface SeccionServicePortType {


    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:updateSeccion")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "updateSeccion", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateSeccion")
    @ResponseWrapper(localName = "updateSeccionResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateSeccionResponse")
    public Integer updateSeccion(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        Seccion bean);

    /**
     * 
     * @param codigo
     * @return
     *     returns net.spring.intranet.entidad.xsd.Seccion
     */
    @WebMethod(action = "urn:findSeccion")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "findSeccion", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindSeccion")
    @ResponseWrapper(localName = "findSeccionResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindSeccionResponse")
    public Seccion findSeccion(
        @WebParam(name = "codigo", targetNamespace = "http://service.intranet.spring.net")
        Integer codigo);

    /**
     * 
     * @param codigo
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:deleteSeccion")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "deleteSeccion", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.DeleteSeccion")
    @ResponseWrapper(localName = "deleteSeccionResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.DeleteSeccionResponse")
    public Integer deleteSeccion(
        @WebParam(name = "codigo", targetNamespace = "http://service.intranet.spring.net")
        Integer codigo);

    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:saveSeccion")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "saveSeccion", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveSeccion")
    @ResponseWrapper(localName = "saveSeccionResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveSeccionResponse")
    public Integer saveSeccion(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        Seccion bean);

    /**
     * 
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.Seccion>
     */
    @WebMethod(action = "urn:listaSecciones")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaSecciones", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaSecciones")
    @ResponseWrapper(localName = "listaSeccionesResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaSeccionesResponse")
    public List<Seccion> listaSecciones();

}
