
package net.spring.intranet.servicio.Horario;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.spring.intranet.entidad.Horario.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HorarioServicePortType", targetNamespace = "http://service.intranet.spring.net")
@XmlSeeAlso({
    net.spring.intranet.entidad.Horario.ObjectFactory.class,
    net.spring.intranet.servicio.Horario.ObjectFactory.class
})
public interface HorarioServicePortType {


    /**
     * 
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.Horario>
     */
    @WebMethod(action = "urn:listaHorario")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaHorario", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaHorario")
    @ResponseWrapper(localName = "listaHorarioResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaHorarioResponse")
    public List<Horario> listaHorario();

}
