
package net.spring.intranet.servicio.Horario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HorarioService", targetNamespace = "http://service.intranet.spring.net", wsdlLocation = "http://localhost:8080/School_Servidor/services/HorarioService?wsdl")
public class HorarioService
    extends Service
{

    private final static URL HORARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException HORARIOSERVICE_EXCEPTION;
    private final static QName HORARIOSERVICE_QNAME = new QName("http://service.intranet.spring.net", "HorarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/School_Servidor/services/HorarioService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HORARIOSERVICE_WSDL_LOCATION = url;
        HORARIOSERVICE_EXCEPTION = e;
    }

    public HorarioService() {
        super(__getWsdlLocation(), HORARIOSERVICE_QNAME);
    }

    public HorarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HORARIOSERVICE_QNAME, features);
    }

    public HorarioService(URL wsdlLocation) {
        super(wsdlLocation, HORARIOSERVICE_QNAME);
    }

    public HorarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HORARIOSERVICE_QNAME, features);
    }

    public HorarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HorarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpSoap11Endpoint")
    public HorarioServicePortType getHorarioServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpSoap11Endpoint"), HorarioServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpSoap11Endpoint")
    public HorarioServicePortType getHorarioServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpSoap11Endpoint"), HorarioServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpSoap12Endpoint")
    public HorarioServicePortType getHorarioServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpSoap12Endpoint"), HorarioServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpSoap12Endpoint")
    public HorarioServicePortType getHorarioServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpSoap12Endpoint"), HorarioServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpEndpoint")
    public HorarioServicePortType getHorarioServiceHttpEndpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpEndpoint"), HorarioServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HorarioServicePortType
     */
    @WebEndpoint(name = "HorarioServiceHttpEndpoint")
    public HorarioServicePortType getHorarioServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "HorarioServiceHttpEndpoint"), HorarioServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HORARIOSERVICE_EXCEPTION!= null) {
            throw HORARIOSERVICE_EXCEPTION;
        }
        return HORARIOSERVICE_WSDL_LOCATION;
    }

}
