
package net.spring.intranet.servicio.Docente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocenteService", targetNamespace = "http://service.intranet.spring.net", wsdlLocation = "http://localhost:8080/School_Servidor/services/DocenteService?wsdl")
public class DocenteService
    extends Service
{

    private final static URL DOCENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCENTESERVICE_EXCEPTION;
    private final static QName DOCENTESERVICE_QNAME = new QName("http://service.intranet.spring.net", "DocenteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/School_Servidor/services/DocenteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCENTESERVICE_WSDL_LOCATION = url;
        DOCENTESERVICE_EXCEPTION = e;
    }

    public DocenteService() {
        super(__getWsdlLocation(), DOCENTESERVICE_QNAME);
    }

    public DocenteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCENTESERVICE_QNAME, features);
    }

    public DocenteService(URL wsdlLocation) {
        super(wsdlLocation, DOCENTESERVICE_QNAME);
    }

    public DocenteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCENTESERVICE_QNAME, features);
    }

    public DocenteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocenteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpSoap11Endpoint")
    public DocenteServicePortType getDocenteServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpSoap11Endpoint"), DocenteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpSoap11Endpoint")
    public DocenteServicePortType getDocenteServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpSoap11Endpoint"), DocenteServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpSoap12Endpoint")
    public DocenteServicePortType getDocenteServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpSoap12Endpoint"), DocenteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpSoap12Endpoint")
    public DocenteServicePortType getDocenteServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpSoap12Endpoint"), DocenteServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpEndpoint")
    public DocenteServicePortType getDocenteServiceHttpEndpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpEndpoint"), DocenteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocenteServicePortType
     */
    @WebEndpoint(name = "DocenteServiceHttpEndpoint")
    public DocenteServicePortType getDocenteServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "DocenteServiceHttpEndpoint"), DocenteServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCENTESERVICE_EXCEPTION!= null) {
            throw DOCENTESERVICE_EXCEPTION;
        }
        return DOCENTESERVICE_WSDL_LOCATION;
    }

}
