
package net.spring.intranet.servicio.Docente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.spring.intranet.entidad.Docente.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocenteServicePortType", targetNamespace = "http://service.intranet.spring.net")
@XmlSeeAlso({
    net.spring.intranet.entidad.Docente.ObjectFactory.class,
    net.spring.intranet.servicio.Docente.ObjectFactory.class
})
public interface DocenteServicePortType {


    /**
     * 
     * @param codigo
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:deleteDocente")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "deleteDocente", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.DeleteDocente")
    @ResponseWrapper(localName = "deleteDocenteResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.DeleteDocenteResponse")
    public Integer deleteDocente(
        @WebParam(name = "codigo", targetNamespace = "http://service.intranet.spring.net")
        Integer codigo);

    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:saveDocente")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "saveDocente", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveDocente")
    @ResponseWrapper(localName = "saveDocenteResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveDocenteResponse")
    public Integer saveDocente(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        Docentes bean);

    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:updateDocente")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "updateDocente", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateDocente")
    @ResponseWrapper(localName = "updateDocenteResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateDocenteResponse")
    public Integer updateDocente(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        Docentes bean);

    /**
     * 
     * @param codigo
     * @return
     *     returns net.spring.intranet.entidad.xsd.Docentes
     */
    @WebMethod(action = "urn:findDocente")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "findDocente", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindDocente")
    @ResponseWrapper(localName = "findDocenteResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindDocenteResponse")
    public Docentes findDocente(
        @WebParam(name = "codigo", targetNamespace = "http://service.intranet.spring.net")
        Integer codigo);

    /**
     * 
     * @param pass
     * @param user
     * @param rol
     * @return
     *     returns net.spring.intranet.entidad.xsd.Docentes
     */
    @WebMethod(action = "urn:iniciarSesion")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "iniciarSesion", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.IniciarSesion")
    @ResponseWrapper(localName = "iniciarSesionResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.IniciarSesionResponse")
    public Docentes iniciarSesion(
        @WebParam(name = "user", targetNamespace = "http://service.intranet.spring.net")
        String user,
        @WebParam(name = "pass", targetNamespace = "http://service.intranet.spring.net")
        String pass,
        @WebParam(name = "rol", targetNamespace = "http://service.intranet.spring.net")
        Integer rol);

    /**
     * 
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.Docentes>
     */
    @WebMethod(action = "urn:listaDocentes")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaDocentes", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDocentes")
    @ResponseWrapper(localName = "listaDocentesResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDocentesResponse")
    public List<Docentes> listaDocentes();

}
