
package net.spring.intranet.servicio.Det_Sec_Alu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.spring.intranet.entidad.Det_Sec_Alu.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Det_Sec_AluServicePortType", targetNamespace = "http://service.intranet.spring.net")
@XmlSeeAlso({
    net.spring.intranet.entidad.Det_Sec_Alu.ObjectFactory.class,
    net.spring.intranet.servicio.Det_Sec_Alu.ObjectFactory.class
})
public interface DetSecAluServicePortType {


    /**
     * 
     * @param cod
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.DetSecAlu>
     */
    @WebMethod(operationName = "listaDet_sec_aluxAlumnos", action = "urn:listaDet_sec_aluxAlumnos")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaDet_sec_aluxAlumnos", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDetSecAluxAlumnos")
    @ResponseWrapper(localName = "listaDet_sec_aluxAlumnosResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDetSecAluxAlumnosResponse")
    public List<DetSecAlu> listaDetSecAluxAlumnos(
        @WebParam(name = "cod", targetNamespace = "http://service.intranet.spring.net")
        Integer cod);

    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:saveDetSecAlu")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "saveDetSecAlu", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveDetSecAlu")
    @ResponseWrapper(localName = "saveDetSecAluResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.SaveDetSecAluResponse")
    public Integer saveDetSecAlu(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        DetSecAlu bean);

    /**
     * 
     * @param bean
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "urn:updateDetSecAlu")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "updateDetSecAlu", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateDetSecAlu")
    @ResponseWrapper(localName = "updateDetSecAluResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.UpdateDetSecAluResponse")
    public Integer updateDetSecAlu(
        @WebParam(name = "bean", targetNamespace = "http://service.intranet.spring.net")
        DetSecAlu bean);

    /**
     * 
     * @return
     *     returns java.util.List<net.spring.intranet.entidad.xsd.DetSecAlu>
     */
    @WebMethod(action = "urn:listaDetSecAlu")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "listaDetSecAlu", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDetSecAlu")
    @ResponseWrapper(localName = "listaDetSecAluResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.ListaDetSecAluResponse")
    public List<DetSecAlu> listaDetSecAlu();

    /**
     * 
     * @param codigo
     * @return
     *     returns net.spring.intranet.entidad.xsd.DetSecAlu
     */
    @WebMethod(action = "urn:findDetSecAlu")
    @WebResult(targetNamespace = "http://service.intranet.spring.net")
    @RequestWrapper(localName = "findDetSecAlu", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindDetSecAlu")
    @ResponseWrapper(localName = "findDetSecAluResponse", targetNamespace = "http://service.intranet.spring.net", className = "net.spring.intranet.service.FindDetSecAluResponse")
    public DetSecAlu findDetSecAlu(
        @WebParam(name = "codigo", targetNamespace = "http://service.intranet.spring.net")
        Integer codigo);

}
