
package net.spring.intranet.servicio.Det_Sec_Alu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Det_Sec_AluService", targetNamespace = "http://service.intranet.spring.net", wsdlLocation = "http://localhost:8080/School_Servidor/services/Det_Sec_AluService?wsdl")
public class DetSecAluService
    extends Service
{

    private final static URL DETSECALUSERVICE_WSDL_LOCATION;
    private final static WebServiceException DETSECALUSERVICE_EXCEPTION;
    private final static QName DETSECALUSERVICE_QNAME = new QName("http://service.intranet.spring.net", "Det_Sec_AluService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/School_Servidor/services/Det_Sec_AluService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETSECALUSERVICE_WSDL_LOCATION = url;
        DETSECALUSERVICE_EXCEPTION = e;
    }

    public DetSecAluService() {
        super(__getWsdlLocation(), DETSECALUSERVICE_QNAME);
    }

    public DetSecAluService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DETSECALUSERVICE_QNAME, features);
    }

    public DetSecAluService(URL wsdlLocation) {
        super(wsdlLocation, DETSECALUSERVICE_QNAME);
    }

    public DetSecAluService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DETSECALUSERVICE_QNAME, features);
    }

    public DetSecAluService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetSecAluService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpSoap11Endpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpSoap11Endpoint"), DetSecAluServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpSoap11Endpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpSoap11Endpoint"), DetSecAluServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpSoap12Endpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpSoap12Endpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpSoap12Endpoint"), DetSecAluServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpSoap12Endpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpSoap12Endpoint"), DetSecAluServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpEndpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpEndpoint() {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpEndpoint"), DetSecAluServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetSecAluServicePortType
     */
    @WebEndpoint(name = "Det_Sec_AluServiceHttpEndpoint")
    public DetSecAluServicePortType getDetSecAluServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.intranet.spring.net", "Det_Sec_AluServiceHttpEndpoint"), DetSecAluServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETSECALUSERVICE_EXCEPTION!= null) {
            throw DETSECALUSERVICE_EXCEPTION;
        }
        return DETSECALUSERVICE_WSDL_LOCATION;
    }

}
